version: '2.1'
services:
    docker_postgres:
        image: postgres:9.6
        container_name: "docker_postgres"
        ports:
          - 5433:5432
        environment:
            POSTGRES_DB: airflow
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD: vv3paY4j0QN6
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata


    webserver:
        image: 145205126837.dkr.ecr.us-east-1.amazonaws.com/airfox-tensorflow-airflow:1.1
        restart: always
        depends_on:
            - docker_postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - ${PWD}:/root/home
            - /mnt:/mnt
            - ${HOME}/.ssh:/root/.ssh
            - ${HOME}/.databases.conf:/root/.databases.conf
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /root/home/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
